class TiledBackground
  def self.ground(tiles_path,min_width)
    TileBackground.new( 64,
                        64,
                        { render_target_name: :ground,
                          width:              min_width,#512,
                          height:             64,
                          speed:              2 },
                        { tiles:  { path:         tiles_path,#'sprites/temple_background_tiles.png',
                                    size:         8 },
                          groups: { horizontal1:  { indices: [ 0, 1, 2, 3 ], offset: [ 1,  0 ] },   
                                    horizontal2:  { indices: [ 0, 1, 2, 3 ], offset: [ 1,  0 ] },
                                    horizontal3:  { indices: [ 0, 1, 2, 3 ], offset: [ 1,  0 ] },
                                    horizontal4:  { indices: [ 0, 1, 2, 3 ], offset: [ 1,  0 ] },
                                    connection:   { indices: [ 0, 1, 2, 3 ], offset: [ 1,  0 ] },
                                    bottom_right: { indices: [ 4 ],          offset: [ 0,  1 ] },
                                    bottom_left:  { indices: [ 5 ],          offset: [ 1,  0 ] },
                                    top_left:     { indices: [ 6 ],          offset: [ 1,  0 ] },
                                    top_right:    { indices: [ 7 ],          offset: [ 0, -1 ] },
                                    empty:        { indices: [ 8 ],          offset: [ 0,  0 ] } },
                          rules:  { horizontal1:  { 1.0  => [ :horizontal2 ] },
                                    horizontal2:  { 1.0  => [ :horizontal3 ] },
                                    horizontal3:  { 1.0  => [ :horizontal4 ] },
                                    horizontal4:  { 0.7  => [ :horizontal4 ], 1.0 => [ :connection ] },
                                    connection:   { 0.8  => [ :connection ], 1.0 => [ :bottom_right, :top_right ] },
                                    bottom_right: { 1.0  => [ :top_left ] },
                                    top_left:     { 1.0  => [ :horizontal1 ] },
                                    top_right:    { 1.0  => [ :bottom_left ] },
                                    bottom_left:  { 1.0  => [ :horizontal1 ] } },
                          fill:   [ 0, 1, 2, 3, 4, 5 ] } )
  end
end
